import chalk from 'chalk';
import { readFileSync } from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

export const AUTHOR = {
  name: 'Akash Chowdhury',
  email: 'akashbumbac24@gmail.com',
  linkedin: 'https://www.linkedin.com/in/akash-chowdhury-12141a222/',
  linkedinShort: 'linkedin.com/in/akash-chowdhury-12141a222',
};

export const TOOL_NAME = 'DeployHub';

/** GitHub repository slug (owner/repo) for releases and install scripts */
export const GITHUB_REPO = 'akashchowdhury/deployhub';

let cachedVersion = null;

/**
 * @returns {string}
 */
export function getDeployHubVersion() {
  if (!cachedVersion) {
    const pkgPath = path.join(
      path.dirname(fileURLToPath(import.meta.url)),
      '../../package.json'
    );
    cachedVersion = JSON.parse(readFileSync(pkgPath, 'utf-8')).version;
  }
  return cachedVersion;
}

/**
 * @returns {string}
 */
export function formatVersionOutput() {
  const version = getDeployHubVersion();
  return `${version}\nBuilt by ${AUTHOR.name} — ${AUTHOR.email}\n${AUTHOR.linkedin}`;
}

/**
 * @returns {object}
 */
export function getGeneratedByMetadata() {
  return {
    tool: TOOL_NAME,
    version: getDeployHubVersion(),
    author: AUTHOR.name,
    email: AUTHOR.email,
    linkedin: AUTHOR.linkedin,
  };
}

/**
 * @returns {string}
 */
export function getArtifactReadmeFooter() {
  return `---
Generated by DeployHub
Built by ${AUTHOR.name} <${AUTHOR.email}>
${AUTHOR.linkedin}

This artifact was automatically created and stored by DeployHub.
`;
}

/**
 * @returns {string}
 */
export function getWorkflowHeaderComment() {
  return `# ─────────────────────────────────────────────
# This workflow was auto-generated by DeployHub
# Built by ${AUTHOR.name} <${AUTHOR.email}>
# ${AUTHOR.linkedin}
# Do not edit this file manually.
# ─────────────────────────────────────────────
`;
}

export function printBanner() {
  const dim = chalk.dim;
  const padLine = (content) => {
    const visible = content.replace(/\u001b\[[0-9;]*m/g, '');
    const padding = Math.max(0, 49 - visible.length);
    return dim('│') + content + ' '.repeat(padding) + dim('│');
  };

  console.log('');
  console.log(dim('┌─────────────────────────────────────────────────┐'));
  console.log(dim('│                                                 │'));
  console.log(padLine('   🚀 ' + chalk.bold.white('DeployHub')));
  console.log(padLine('   ' + chalk.cyan(`Built by ${AUTHOR.name}`)));
  console.log(padLine('   ' + chalk.gray(AUTHOR.email)));
  console.log(padLine('   ' + chalk.gray(AUTHOR.linkedinShort)));
  console.log(dim('│                                                 │'));
  console.log(dim('└─────────────────────────────────────────────────┘'));
  console.log('');
}

export function printAuthorFooter() {
  console.log(chalk.dim('─────────────────────────────────────────────'));
  console.log(chalk.cyan(`  Built with ❤ by ${AUTHOR.name}`));
  console.log('  Questions or feedback?');
  console.log(chalk.gray(`  📧  ${AUTHOR.email}`));
  console.log(chalk.gray(`  💼  ${AUTHOR.linkedinShort}`));
  console.log(chalk.dim('─────────────────────────────────────────────'));
  console.log('');
}

export function printDoctorFooter() {
  console.log(
    chalk.gray(`  DeployHub by ${AUTHOR.name} — ${AUTHOR.email}`)
  );
}

/**
 * @returns {boolean}
 */
export function shouldShowBanner() {
  const args = process.argv.slice(2);
  if (args.includes('--help') || args.includes('-h')) return false;
  if (args.includes('--version') || args.includes('-V')) return false;
  const subcommand = args.find((arg) => !arg.startsWith('-'));
  return Boolean(subcommand);
}

export default {
  AUTHOR,
  TOOL_NAME,
  GITHUB_REPO,
  getDeployHubVersion,
  formatVersionOutput,
  getGeneratedByMetadata,
  getArtifactReadmeFooter,
  getWorkflowHeaderComment,
  printBanner,
  printAuthorFooter,
  printDoctorFooter,
  shouldShowBanner,
};
