/**
 * Dockerfile generation based on detected framework / project settings.
 */

const GENERATED_HEADER =
  '# Generated by DeployHub — review exposed port and start command before deploying.\n';

const DOCKERIGNORE_HEADER =
  '# Generated by DeployHub — safe to edit. Existing .dockerignore is never overwritten.\n';

/**
 * @param {string} projectName
 * @returns {string}
 */
export function sanitizeDockerProjectName(projectName) {
  return projectName.replace(/[^a-zA-Z0-9_-]/g, '-');
}

/**
 * @param {import('../core/config.js').DeployHubConfig} config
 * @returns {{ framework: string, buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number, projectType: string }}
 */
export function resolveDockerSettings(config) {
  const projectType = config.projectType || 'frontend';

  if (projectType === 'both' && config.backend) {
    const framework = config.backend.framework || 'express';
    return {
      framework,
      buildCommand: config.backend.buildCommand ?? null,
      buildOutput: config.backend.buildOutput || defaultBuildOutput(framework, projectType),
      // null lets each generator supply a language-correct CMD (do not force npm start).
      startCommand: config.backend.startCommand ?? null,
      port: config.backend.port || defaultPort(framework, projectType),
      projectType,
    };
  }

  const framework =
    config.framework || (projectType === 'frontend' ? 'react' : 'express');
  return {
    framework,
    buildCommand: config.buildCommand ?? null,
    buildOutput: config.buildOutput || defaultBuildOutput(framework, projectType),
    startCommand: config.startCommand ?? null,
    port: config.port || defaultPort(framework, projectType),
    projectType,
  };
}

/**
 * @param {string} framework
 * @param {string} projectType
 */
function defaultBuildOutput(framework, projectType) {
  if (
    projectType === 'frontend' ||
    ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'].includes(framework)
  ) {
    return 'dist';
  }
  if (framework === 'nestjs') return 'dist';
  if (framework === 'dotnet') return 'publish';
  if (framework === 'spring' || framework === 'java') return 'target';
  if (framework === 'go') return 'bin';
  return '.';
}

/**
 * @param {string} framework
 * @param {string} projectType
 */
function defaultPort(framework, projectType) {
  if (
    projectType === 'frontend' ||
    ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'].includes(framework)
  ) {
    return 80;
  }
  if (['laravel', 'symfony', 'php'].includes(framework)) return 80;
  if (['fastapi', 'django', 'python'].includes(framework)) return 8000;
  if (framework === 'flask') return 5000;
  if (['spring', 'java', 'go'].includes(framework)) return 8080;
  if (framework === 'dotnet') return 5000;
  if (framework === 'rails') return 3000;
  if (framework === 'ruby') return 9292;
  return 3000;
}

/**
 * Generate a .dockerignore matching the Dockerfile language/framework.
 * @param {import('../core/config.js').DeployHubConfig} config
 * @returns {string}
 */
export function generateDockerignore(config) {
  const settings = resolveDockerSettings(config);
  const { framework, buildOutput, projectType } = settings;

  /** @type {string[]} */
  const lines = [DOCKERIGNORE_HEADER.trimEnd(), ''];

  const common = [
    '.git',
    '.gitignore',
    '.env',
    '.env.*',
    '!.env.example',
    'artifact',
    '.deployhub',
    'coverage',
    '*.md',
    '!README.md',
    '.github',
    '.vscode',
    '.idea',
    'deployhub.config.json',
  ];
  lines.push(...common, '');

  const frontendStatic = ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'];
  const nodeFrameworks = [
    ...frontendStatic,
    'nextjs',
    'nestjs',
    'express',
    'fastify',
    'koa',
    'node',
  ];
  const pythonFrameworks = ['fastapi', 'django', 'flask', 'python'];
  const phpFrameworks = ['laravel', 'symfony', 'php'];

  if (nodeFrameworks.includes(framework) || !framework) {
    lines.push('node_modules', 'npm-debug.log*', 'yarn-error.log*', '.npm', '');
    // Source Dockerfile rebuilds inside the image — exclude local build output from context
    if (
      frontendStatic.includes(framework) ||
      framework === 'nextjs' ||
      framework === 'nestjs' ||
      (projectType === 'frontend' && buildOutput && buildOutput !== '.')
    ) {
      const out = buildOutput || 'dist';
      if (out !== '.') lines.push(out);
      if (framework === 'nextjs') lines.push('.next');
      if (out !== 'build') lines.push('build');
      lines.push('');
    }
  }

  if (pythonFrameworks.includes(framework)) {
    lines.push(
      '__pycache__',
      '*.py[cod]',
      '.venv',
      'venv',
      '.pytest_cache',
      '*.egg-info',
      ''
    );
  }

  if (phpFrameworks.includes(framework)) {
    lines.push('vendor', '');
  }

  if (framework === 'spring' || framework === 'java') {
    lines.push('target', '.gradle', 'build', '');
  }

  if (framework === 'go') {
    lines.push('bin', '');
  }

  if (framework === 'dotnet') {
    lines.push('bin', 'obj', '');
  }

  if (framework === 'rails' || framework === 'ruby') {
    lines.push('tmp', 'log', 'vendor/bundle', '');
  }

  return `${lines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`;
}

/**
 * @param {import('../core/config.js').DeployHubConfig} config
 * @returns {string}
 */
export function generateDockerfile(config) {
  const settings = resolveDockerSettings(config);
  const { framework } = settings;

  const frontendStatic = ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'];
  if (frontendStatic.includes(framework)) {
    return generateFrontendStaticDockerfile(settings);
  }

  switch (framework) {
    case 'nextjs':
      return generateNextjsDockerfile(settings);
    case 'nestjs':
      return generateNestjsDockerfile(settings);
    case 'express':
    case 'fastify':
    case 'koa':
    case 'node':
      return generateNodeBackendDockerfile(settings);
    case 'fastapi':
      return generateFastapiDockerfile(settings);
    case 'django':
      return generateDjangoDockerfile(settings);
    case 'flask':
      return generateFlaskDockerfile(settings);
    case 'python':
      return generatePythonDockerfile(settings);
    case 'laravel':
      return generateLaravelDockerfile(settings);
    case 'symfony':
      return generateSymfonyDockerfile(settings);
    case 'php':
      return generatePhpDockerfile(settings);
    case 'spring':
    case 'java':
      return generateSpringDockerfile(settings);
    case 'go':
      return generateGoDockerfile(settings);
    case 'dotnet':
      return generateDotnetDockerfile(settings);
    case 'rails':
      return generateRailsDockerfile(settings);
    case 'ruby':
      return generateRubyDockerfile(settings);
    default:
      return generateNodeBackendDockerfile(settings);
  }
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, port: number }} settings
 */
function generateFrontendStaticDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'npm run build';
  const output = settings.buildOutput || 'dist';

  return `${GENERATED_HEADER}
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN ${buildCmd}

FROM nginx:alpine
COPY --from=build /app/${output} /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

/**
 * @param {{ buildCommand: string|null, startCommand: string|null, port: number }} settings
 */
function generateNextjsDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'npm run build';
  const startCmd = settings.startCommand || 'npm start';
  const port = settings.port || 3000;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN ${buildCmd}

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number }} settings
 */
function generateNestjsDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'npm run build';
  const startCmd = settings.startCommand || 'node dist/main';
  const port = settings.port || 3000;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN ${buildCmd}

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/${settings.buildOutput || 'dist'} ./${settings.buildOutput || 'dist'}
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number }} settings
 */
function generateNodeBackendDockerfile(settings) {
  const port = settings.port || 3000;
  const startCmd = settings.startCommand || 'npm start';
  const startParts = parseCommand(startCmd);

  if (settings.buildCommand) {
    return `${GENERATED_HEADER}
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN ${settings.buildCommand}

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/${settings.buildOutput || '.'} ./${settings.buildOutput || '.'}
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
  }

  return `${GENERATED_HEADER}
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateFastapiDockerfile(settings) {
  const port = settings.port || 8000;
  const startCmd = settings.startCommand || `uvicorn main:app --host 0.0.0.0 --port ${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM python:3.11-slim AS build
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateDjangoDockerfile(settings) {
  const port = settings.port || 8000;
  const startCmd =
    settings.startCommand || `gunicorn config.wsgi:application --bind 0.0.0.0:${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM python:3.11-slim AS build
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateFlaskDockerfile(settings) {
  const port = settings.port || 5000;
  const startCmd = settings.startCommand || `gunicorn app:app --bind 0.0.0.0:${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM python:3.11-slim AS build
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * Plain Python (no FastAPI/Django/Flask): optional requirements + stdlib HTTP server.
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generatePythonDockerfile(settings) {
  const port = settings.port || 8000;
  const startCmd =
    settings.startCommand || `python -m http.server ${port} --bind 0.0.0.0`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM python:3.11-slim
WORKDIR /app
COPY requirements.txt* ./
RUN if [ -f requirements.txt ]; then pip install --no-cache-dir -r requirements.txt; fi
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ port: number }} settings
 */
function generateLaravelDockerfile(settings) {
  const port = settings.port || 80;
  // Single-process HTTP for container/K8s fitness. SSH deploys still use host
  // php-fpm + nginx; this image must listen on EXPOSE (FPM alone listens on 9000).
  const cmd = JSON.stringify([
    'php',
    'artisan',
    'serve',
    '--host=0.0.0.0',
    `--port=${port}`,
  ]);

  // Vendor stage copies only composer.json/lock for layer caching. Laravel's
  // post-autoload-dump runs `php artisan package:discover`, which needs the
  // full app — so install with --no-scripts here, then dump-autoload after COPY.
  return `${GENERATED_HEADER}
FROM composer:2 AS vendor
WORKDIR /app
COPY composer.json composer.lock* ./
RUN composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs --no-scripts

FROM php:8.2-cli-alpine
WORKDIR /var/www/html
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN apk add --no-cache icu-libs libzip \\
  && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS icu-dev libzip-dev oniguruma-dev \\
  && docker-php-ext-install -j$(nproc) pdo_mysql mbstring zip opcache \\
  && apk del .build-deps
COPY --from=vendor /app/vendor ./vendor
COPY . .
RUN composer dump-autoload --optimize --no-dev --no-interaction
RUN chown -R www-data:www-data storage bootstrap/cache || true
EXPOSE ${port}
CMD ${cmd}
`;
}

/**
 * @param {{ port: number }} settings
 */
function generateSymfonyDockerfile(settings) {
  const port = settings.port || 80;
  // Built-in server binds HTTP to EXPOSE — suitable for a single-container pod.
  // Prefer a production reverse-proxy image if you outgrow this starter template.
  const cmd = JSON.stringify(['php', '-S', `0.0.0.0:${port}`, '-t', 'public']);

  // Same as Laravel: vendor stage has no app source, so skip Composer scripts
  // (Flex recipes / auto-scripts often need bin/console & the project tree).
  return `${GENERATED_HEADER}
FROM composer:2 AS vendor
WORKDIR /app
COPY composer.json composer.lock* ./
RUN composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs --no-scripts

FROM php:8.2-cli-alpine
WORKDIR /var/www/html
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN apk add --no-cache icu-libs libzip \\
  && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS icu-dev libzip-dev oniguruma-dev \\
  && docker-php-ext-install -j$(nproc) pdo_mysql mbstring zip opcache \\
  && apk del .build-deps
COPY --from=vendor /app/vendor ./vendor
COPY . .
RUN composer dump-autoload --optimize --no-dev --no-interaction
EXPOSE ${port}
CMD ${cmd}
`;
}

/**
 * Plain PHP (no Laravel/Symfony): single-process built-in server.
 * Docroot prefers public/ at runtime when present; optional composer install.
 * @param {{ port: number }} settings
 */
function generatePhpDockerfile(settings) {
  const port = settings.port || 80;
  const cmd = JSON.stringify([
    'sh',
    '-c',
    `d=.; [ -d public ] && d=public; exec php -S 0.0.0.0:${port} -t "$d"`,
  ]);

  return `${GENERATED_HEADER}
FROM php:8.2-cli-alpine
WORKDIR /var/www/html
COPY --from=composer:2 /usr/bin/composer /usr/bin/composer
RUN apk add --no-cache icu-libs libzip \\
  && apk add --no-cache --virtual .build-deps $PHPIZE_DEPS icu-dev libzip-dev oniguruma-dev \\
  && docker-php-ext-install -j$(nproc) pdo_mysql mbstring zip opcache \\
  && apk del .build-deps
COPY . .
RUN if [ -f composer.json ]; then composer install --no-dev --optimize-autoloader --no-interaction --ignore-platform-reqs; fi
EXPOSE ${port}
CMD ${cmd}
`;
}

/**
 * @param {{ buildCommand: string|null, port: number }} settings
 */
function generateSpringDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'mvn package -DskipTests';
  const port = settings.port || 8080;

  return `${GENERATED_HEADER}
FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN apk add --no-cache maven && ${buildCmd} \\
  && JAR=$(ls target/*.jar 2>/dev/null | grep -v '\\-plain\\.jar$' | head -n1) \\
  && test -n "$JAR" && cp "$JAR" /app/app.jar

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/app.jar app.jar
EXPOSE ${port}
CMD ["java", "-jar", "app.jar"]
`;
}

/**
 * @param {{ buildCommand: string|null, startCommand: string|null, port: number }} settings
 */
function generateGoDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'go build -o /app/bin/app .';
  const port = settings.port || 8080;

  return `${GENERATED_HEADER}
FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum* ./
RUN go mod download
COPY . .
RUN mkdir -p /app/bin && ${buildCmd}

FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=build /app/bin/app ./app
EXPOSE ${port}
CMD ["./app"]
`;
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number }} settings
 */
function generateDotnetDockerfile(settings) {
  // Publish into a path under WORKDIR so the runtime stage COPY path matches.
  const buildCmd = settings.buildCommand || 'dotnet publish -c Release -o publish';
  const port = settings.port || 5000;
  const output = settings.buildOutput || 'publish';

  return `${GENERATED_HEADER}
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore
COPY . .
RUN ${buildCmd}

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /src/${output} .
EXPOSE ${port}
ENV ASPNETCORE_URLS=http://+:${port}
CMD ["dotnet", "App.dll"]
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateRailsDockerfile(settings) {
  const port = settings.port || 3000;
  // Bind explicitly — puma.rb / SSH assumptions are not the container PID 1 contract.
  const startCmd =
    settings.startCommand || `bundle exec puma -b tcp://0.0.0.0:${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM ruby:3.2-slim AS build
WORKDIR /app
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock* ./
RUN bundle config set --local without 'development test' && bundle install
COPY . .
RUN bundle exec rake assets:precompile || true

FROM ruby:3.2-slim
WORKDIR /app
RUN apt-get update -qq && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build /app .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * Plain Ruby / Rack (no Rails): Puma as foreground HTTP process.
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateRubyDockerfile(settings) {
  const port = settings.port || 9292;
  const startCmd =
    settings.startCommand || `bundle exec puma -b tcp://0.0.0.0:${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM ruby:3.2-slim
WORKDIR /app
RUN apt-get update -qq && apt-get install -y build-essential && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock* ./
RUN bundle config set --local without 'development test' && bundle install
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {string} command
 * @returns {string[]}
 */
function parseCommand(command) {
  const trimmed = command.trim();
  if (trimmed.startsWith('[')) {
    try {
      return JSON.parse(trimmed);
    } catch {
      // fall through
    }
  }

  const match = trimmed.match(/^(\S+)(?:\s+(.*))?$/);
  if (!match) return ['sh', '-c', trimmed];
  const [, bin, rest] = match;
  if (!rest) return [bin];
  return [bin, ...rest.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g).map((part) => part.replace(/^['"]|['"]$/g, ''))];
}

/**
 * Human-readable framework label for user messages.
 * @param {string} framework
 */
export function getDockerfileFrameworkLabel(framework) {
  const labels = {
    react: 'React',
    vue: 'Vue',
    angular: 'Angular',
    nextjs: 'Next.js',
    svelte: 'Svelte',
    astro: 'Astro',
    vanilla: 'Vanilla JS',
    express: 'Express',
    nestjs: 'NestJS',
    fastify: 'Fastify',
    koa: 'Koa',
    fastapi: 'FastAPI',
    django: 'Django',
    flask: 'Flask',
    laravel: 'Laravel',
    symfony: 'Symfony',
    php: 'PHP',
    python: 'Python',
    node: 'Node.js',
    java: 'Java',
    ruby: 'Ruby',
    spring: 'Spring Boot',
    go: 'Go',
    dotnet: '.NET',
    rails: 'Ruby on Rails',
  };
  return labels[framework] || framework;
}

export default {
  generateDockerfile,
  generateDockerignore,
  resolveDockerSettings,
  sanitizeDockerProjectName,
  getDockerfileFrameworkLabel,
};
