/**
 * Shared Docker image naming for pipeline builds and deploy.
 */

/**
 * @param {import('../core/config.js').DeployHubConfig} config
 * @param {Record<string, string|undefined>} [env]
 * @returns {{
 *   imageName: string,
 *   imageTag: string,
 *   fullImage: string,
 *   latestImage: string,
 *   legacyLatestImage: string,
 * }}
 */
export function resolveDockerImageRef(config, env = process.env) {
  const imageName = env.DOCKER_IMAGE_NAME || config.project;
  const imageTag = env.DOCKER_IMAGE_TAG || config.version || 'latest';
  const registryUrl = env.DOCKER_REGISTRY_URL || '';

  const repository =
    registryUrl && !imageName.includes('/')
      ? `${registryUrl.replace(/\/$/, '')}/${imageName}`
      : imageName;

  return {
    imageName,
    imageTag,
    fullImage: `${repository}:${imageTag}`,
    latestImage: `${repository}:latest`,
    legacyLatestImage: `${config.project}:latest`,
  };
}

/**
 * Runtime-only Dockerfile for frontend artifacts that already contain built static output.
 * Used when deploy must build from an artifact (no source / no package-lock).
 * @param {string} [buildOutput]
 * @returns {string}
 */
export function generateFrontendRuntimeDockerfile(buildOutput = 'dist') {
  const output = buildOutput.replace(/^\/+|\/+$/g, '') || 'dist';
  return `# Generated by DeployHub for artifact deploy (pre-built static output)
FROM nginx:alpine
COPY ${output}/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

/**
 * @param {string} jarRelativePath e.g. target/app.jar
 * @param {number} [port]
 */
export function generateSpringRuntimeDockerfile(jarRelativePath, port = 8080) {
  return `# Generated by DeployHub for artifact deploy (pre-built JAR)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY ${jarRelativePath} app.jar
EXPOSE ${port}
CMD ["java", "-jar", "app.jar"]
`;
}

/**
 * @param {string} binaryRelativePath e.g. bin/app
 * @param {number} [port]
 */
export function generateGoRuntimeDockerfile(binaryRelativePath, port = 8080) {
  return `# Generated by DeployHub for artifact deploy (pre-built Go binary)
FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY ${binaryRelativePath} ./app
RUN chmod +x ./app
EXPOSE ${port}
CMD ["./app"]
`;
}

/**
 * @param {string} publishDir
 * @param {number} [port]
 */
export function generateDotnetRuntimeDockerfile(publishDir = 'publish', port = 5000) {
  const dir = publishDir.replace(/^\/+|\/+$/g, '') || 'publish';
  return `# Generated by DeployHub for artifact deploy (pre-built .NET publish output)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY ${dir}/ .
EXPOSE ${port}
ENV ASPNETCORE_URLS=http://+:${port}
CMD ["dotnet", "App.dll"]
`;
}

/**
 * @param {string} framework
 * @returns {boolean}
 */
export function isFrontendStaticFramework(framework) {
  return ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'].includes(framework || '');
}

/**
 * Node-style backends whose generated Dockerfiles run npm ci and need a lockfile.
 * @param {string} framework
 */
export function isNodeBackendFramework(framework) {
  return ['express', 'nestjs', 'fastify', 'koa', 'nextjs'].includes(framework || '');
}

/**
 * Interpreted backends that install deps at image-build time (pip/composer/bundle/npm).
 * Their artifacts lack vendor/venv/node_modules, so standalone artifact rebuild is unsupported.
 * @param {string} framework
 */
export function isInterpretedBackendFramework(framework) {
  return [
    ...['express', 'nestjs', 'fastify', 'koa', 'nextjs'],
    'fastapi',
    'django',
    'flask',
    'laravel',
    'symfony',
    'rails',
  ].includes(framework || '');
}

/**
 * Human-readable dependency gap for interpreted backend artifact rebuilds.
 * @param {string} framework
 * @returns {{ ecosystem: string, missing: string, installCmd: string }}
 */
export function describeInterpretedBackendGap(framework) {
  if (isNodeBackendFramework(framework)) {
    return {
      ecosystem: 'Node',
      missing: 'package-lock.json / node_modules',
      installCmd: 'npm ci',
    };
  }
  if (['fastapi', 'django', 'flask'].includes(framework)) {
    return {
      ecosystem: 'Python',
      missing: 'a pre-installed virtualenv / site-packages (artifacts only ship requirements.txt + source)',
      installCmd: 'pip install',
    };
  }
  if (['laravel', 'symfony'].includes(framework)) {
    return {
      ecosystem: 'PHP',
      missing: 'vendor/ (Composer dependencies are not packaged into the artifact)',
      installCmd: 'composer install',
    };
  }
  if (framework === 'rails') {
    return {
      ecosystem: 'Ruby',
      missing: 'vendor/bundle / installed gems (artifacts only ship Gemfile + lock)',
      installCmd: 'bundle install',
    };
  }
  return {
    ecosystem: 'backend',
    missing: 'installed dependencies (not packaged into the artifact)',
    installCmd: 'dependency install',
  };
}

export default {
  resolveDockerImageRef,
  generateFrontendRuntimeDockerfile,
  generateSpringRuntimeDockerfile,
  generateGoRuntimeDockerfile,
  generateDotnetRuntimeDockerfile,
  isFrontendStaticFramework,
  isNodeBackendFramework,
  isInterpretedBackendFramework,
  describeInterpretedBackendGap,
};
