/**
 * Dockerfile generation based on detected framework / project settings.
 */

const GENERATED_HEADER =
  '# Generated by DeployHub — review exposed port and start command before deploying.\n';

/**
 * @param {string} projectName
 * @returns {string}
 */
export function sanitizeDockerProjectName(projectName) {
  return projectName.replace(/[^a-zA-Z0-9_-]/g, '-');
}

/**
 * @param {import('../core/config.js').DeployHubConfig} config
 * @returns {{ framework: string, buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number, projectType: string }}
 */
export function resolveDockerSettings(config) {
  const projectType = config.projectType || 'frontend';

  if (projectType === 'both' && config.backend) {
    return {
      framework: config.backend.framework || 'express',
      buildCommand: config.backend.buildCommand ?? null,
      buildOutput: config.backend.buildOutput || '.',
      startCommand: config.backend.startCommand || 'npm start',
      port: config.backend.port || 3000,
      projectType,
    };
  }

  return {
    framework: config.framework || 'express',
    buildCommand: config.buildCommand ?? null,
    buildOutput: config.buildOutput || 'dist',
    startCommand: config.startCommand || 'npm start',
    port: config.port || 3000,
    projectType,
  };
}

/**
 * @param {import('../core/config.js').DeployHubConfig} config
 * @returns {string}
 */
export function generateDockerfile(config) {
  const settings = resolveDockerSettings(config);
  const { framework } = settings;

  const frontendStatic = ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'];
  if (frontendStatic.includes(framework)) {
    return generateFrontendStaticDockerfile(settings);
  }

  switch (framework) {
    case 'nextjs':
      return generateNextjsDockerfile(settings);
    case 'nestjs':
      return generateNestjsDockerfile(settings);
    case 'express':
    case 'fastify':
    case 'koa':
      return generateNodeBackendDockerfile(settings);
    case 'fastapi':
      return generateFastapiDockerfile(settings);
    case 'django':
      return generateDjangoDockerfile(settings);
    case 'flask':
      return generateFlaskDockerfile(settings);
    case 'laravel':
      return generateLaravelDockerfile(settings);
    case 'symfony':
      return generateSymfonyDockerfile(settings);
    case 'spring':
      return generateSpringDockerfile(settings);
    case 'go':
      return generateGoDockerfile(settings);
    case 'dotnet':
      return generateDotnetDockerfile(settings);
    case 'rails':
      return generateRailsDockerfile(settings);
    default:
      return generateNodeBackendDockerfile(settings);
  }
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, port: number }} settings
 */
function generateFrontendStaticDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'npm run build';
  const output = settings.buildOutput || 'dist';

  return `${GENERATED_HEADER}
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN ${buildCmd}

FROM nginx:alpine
COPY --from=build /app/${output} /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

/**
 * @param {{ buildCommand: string|null, startCommand: string|null, port: number }} settings
 */
function generateNextjsDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'npm run build';
  const startCmd = settings.startCommand || 'npm start';
  const port = settings.port || 3000;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci

FROM node:20-alpine AS build
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .
RUN ${buildCmd}

FROM node:20-alpine AS runner
WORKDIR /app
ENV NODE_ENV=production
COPY --from=build /app/package*.json ./
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/.next ./.next
COPY --from=build /app/public ./public
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number }} settings
 */
function generateNestjsDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'npm run build';
  const startCmd = settings.startCommand || 'node dist/main';
  const port = settings.port || 3000;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN ${buildCmd}

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/${settings.buildOutput || 'dist'} ./${settings.buildOutput || 'dist'}
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number }} settings
 */
function generateNodeBackendDockerfile(settings) {
  const port = settings.port || 3000;
  const startCmd = settings.startCommand || 'npm start';
  const startParts = parseCommand(startCmd);

  if (settings.buildCommand) {
    return `${GENERATED_HEADER}
FROM node:20-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN ${settings.buildCommand}

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY package*.json ./
RUN npm ci --omit=dev
COPY --from=build /app/${settings.buildOutput || '.'} ./${settings.buildOutput || '.'}
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
  }

  return `${GENERATED_HEADER}
FROM node:20-alpine AS deps
WORKDIR /app
COPY package*.json ./
RUN npm ci --omit=dev

FROM node:20-alpine
WORKDIR /app
ENV NODE_ENV=production
COPY --from=deps /app/node_modules ./node_modules
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateFastapiDockerfile(settings) {
  const port = settings.port || 8000;
  const startCmd = settings.startCommand || `uvicorn main:app --host 0.0.0.0 --port ${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM python:3.11-slim AS build
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateDjangoDockerfile(settings) {
  const port = settings.port || 8000;
  const startCmd =
    settings.startCommand || `gunicorn config.wsgi:application --bind 0.0.0.0:${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM python:3.11-slim AS build
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateFlaskDockerfile(settings) {
  const port = settings.port || 5000;
  const startCmd = settings.startCommand || `gunicorn app:app --bind 0.0.0.0:${port}`;
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM python:3.11-slim AS build
WORKDIR /app
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

FROM python:3.11-slim
WORKDIR /app
COPY --from=build /usr/local/lib/python3.11/site-packages /usr/local/lib/python3.11/site-packages
COPY --from=build /usr/local/bin /usr/local/bin
COPY . .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {{ port: number }} settings
 */
function generateLaravelDockerfile(settings) {
  const port = settings.port || 80;

  return `${GENERATED_HEADER}
FROM composer:2 AS vendor
WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction

FROM php:8.2-fpm-alpine
WORKDIR /var/www/html
COPY --from=vendor /app/vendor ./vendor
COPY . .
RUN chown -R www-data:www-data storage bootstrap/cache || true
EXPOSE ${port}
CMD ["php-fpm"]
`;
}

/**
 * @param {{ port: number }} settings
 */
function generateSymfonyDockerfile(settings) {
  const port = settings.port || 80;

  return `${GENERATED_HEADER}
FROM composer:2 AS vendor
WORKDIR /app
COPY composer.json composer.lock ./
RUN composer install --no-dev --optimize-autoloader --no-interaction

FROM php:8.2-fpm-alpine
WORKDIR /var/www/html
COPY --from=vendor /app/vendor ./vendor
COPY . .
EXPOSE ${port}
CMD ["php-fpm"]
`;
}

/**
 * @param {{ buildCommand: string|null, port: number }} settings
 */
function generateSpringDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'mvn package -DskipTests';
  const port = settings.port || 8080;

  return `${GENERATED_HEADER}
FROM eclipse-temurin:17-jdk-alpine AS build
WORKDIR /app
COPY pom.xml ./
COPY src ./src
RUN apk add --no-cache maven && ${buildCmd}

FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar
EXPOSE ${port}
CMD ["java", "-jar", "app.jar"]
`;
}

/**
 * @param {{ buildCommand: string|null, startCommand: string|null, port: number }} settings
 */
function generateGoDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'go build -o /app/bin/app .';
  const port = settings.port || 8080;

  return `${GENERATED_HEADER}
FROM golang:1.22-alpine AS build
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN ${buildCmd}

FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY --from=build /app/bin/app ./app
EXPOSE ${port}
CMD ["./app"]
`;
}

/**
 * @param {{ buildCommand: string|null, buildOutput: string, startCommand: string|null, port: number }} settings
 */
function generateDotnetDockerfile(settings) {
  const buildCmd = settings.buildCommand || 'dotnet publish -c Release -o /app/publish';
  const port = settings.port || 5000;
  const output = settings.buildOutput || 'publish';

  return `${GENERATED_HEADER}
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY *.csproj ./
RUN dotnet restore
COPY . .
RUN ${buildCmd}

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY --from=build /src/${output} .
EXPOSE ${port}
ENV ASPNETCORE_URLS=http://+:${port}
CMD ["dotnet", "App.dll"]
`;
}

/**
 * @param {{ startCommand: string|null, port: number }} settings
 */
function generateRailsDockerfile(settings) {
  const port = settings.port || 3000;
  const startCmd = settings.startCommand || 'bundle exec puma -C config/puma.rb';
  const startParts = parseCommand(startCmd);

  return `${GENERATED_HEADER}
FROM ruby:3.2-slim AS build
WORKDIR /app
RUN apt-get update -qq && apt-get install -y build-essential libpq-dev && rm -rf /var/lib/apt/lists/*
COPY Gemfile Gemfile.lock ./
RUN bundle install --without development test
COPY . .
RUN bundle exec rake assets:precompile || true

FROM ruby:3.2-slim
WORKDIR /app
RUN apt-get update -qq && apt-get install -y libpq-dev && rm -rf /var/lib/apt/lists/*
COPY --from=build /usr/local/bundle /usr/local/bundle
COPY --from=build /app .
EXPOSE ${port}
CMD ${JSON.stringify(startParts)}
`;
}

/**
 * @param {string} command
 * @returns {string[]}
 */
function parseCommand(command) {
  const trimmed = command.trim();
  if (trimmed.startsWith('[')) {
    try {
      return JSON.parse(trimmed);
    } catch {
      // fall through
    }
  }

  const match = trimmed.match(/^(\S+)(?:\s+(.*))?$/);
  if (!match) return ['sh', '-c', trimmed];
  const [, bin, rest] = match;
  if (!rest) return [bin];
  return [bin, ...rest.match(/(?:[^\s"']+|"[^"]*"|'[^']*')+/g).map((part) => part.replace(/^['"]|['"]$/g, ''))];
}

/**
 * Human-readable framework label for user messages.
 * @param {string} framework
 */
export function getDockerfileFrameworkLabel(framework) {
  const labels = {
    react: 'React',
    vue: 'Vue',
    angular: 'Angular',
    nextjs: 'Next.js',
    svelte: 'Svelte',
    astro: 'Astro',
    vanilla: 'Vanilla JS',
    express: 'Express',
    nestjs: 'NestJS',
    fastify: 'Fastify',
    koa: 'Koa',
    fastapi: 'FastAPI',
    django: 'Django',
    flask: 'Flask',
    laravel: 'Laravel',
    symfony: 'Symfony',
    spring: 'Spring Boot',
    go: 'Go',
    dotnet: '.NET',
    rails: 'Ruby on Rails',
  };
  return labels[framework] || framework;
}

export default {
  generateDockerfile,
  resolveDockerSettings,
  sanitizeDockerProjectName,
  getDockerfileFrameworkLabel,
};
