/**
 * Shared Docker image naming for pipeline builds and deploy.
 */

import { execFileSync } from 'child_process';

/** @typedef {'explicit'|'git'|'ci'|'timestamp'} ImageTagSource */

export const EXPLICIT_IMAGE_TAG_WARNING =
  'DOCKER_IMAGE_TAG is set — reusing the same tag across deploys can leave Kubernetes pods on a stale image (imagePullPolicy defaults to IfNotPresent) unless imagePullPolicy is Always or a rollout restart runs.';

/**
 * High-resolution timestamp for image tags only (artifact versioning keeps getDateVersion()).
 * Minute prefix matches getDateVersion(); seconds+ms avoid collisions in fast rebuild loops.
 * @param {Date} [now]
 * @returns {string}
 */
export function highResImageTagFallback(now = new Date()) {
  const y = now.getFullYear();
  const m = String(now.getMonth() + 1).padStart(2, '0');
  const d = String(now.getDate()).padStart(2, '0');
  const h = String(now.getHours()).padStart(2, '0');
  const min = String(now.getMinutes()).padStart(2, '0');
  const sec = String(now.getSeconds()).padStart(2, '0');
  const ms = String(now.getMilliseconds()).padStart(3, '0');
  return `${y}.${m}.${d}.${h}${min}-${sec}${ms}`;
}

/**
 * @returns {string|null}
 */
function defaultGetGitShortSha() {
  try {
    const sha = execFileSync('git', ['rev-parse', '--short', 'HEAD'], {
      encoding: 'utf8',
      stdio: ['ignore', 'pipe', 'ignore'],
    }).trim();
    return sha || null;
  } catch {
    return null;
  }
}

/**
 * Resolve image tag when DOCKER_IMAGE_TAG is unset: git SHA → CI id → high-res timestamp.
 * Does not use config.version (static package versions would prevent redeploys).
 *
 * @param {Record<string, string|undefined>} [env]
 * @param {{
 *   getGitShortSha?: () => string|null,
 *   now?: () => Date,
 * }} [options]
 * @returns {{ imageTag: string, tagSource: ImageTagSource }}
 */
export function resolveImageTag(env = process.env, options = {}) {
  const explicit = env.DOCKER_IMAGE_TAG;
  if (explicit) {
    return { imageTag: explicit, tagSource: 'explicit' };
  }

  const getGitShortSha = options.getGitShortSha || defaultGetGitShortSha;
  const gitSha = getGitShortSha();
  if (gitSha) {
    return { imageTag: gitSha, tagSource: 'git' };
  }

  const ciTag =
    (env.GITHUB_SHA && String(env.GITHUB_SHA).slice(0, 7)) ||
    env.GITHUB_RUN_ID ||
    env.CI_COMMIT_SHORT_SHA ||
    env.CI_PIPELINE_ID;
  if (ciTag) {
    return { imageTag: String(ciTag), tagSource: 'ci' };
  }

  const now = options.now ? options.now() : new Date();
  return { imageTag: highResImageTagFallback(now), tagSource: 'timestamp' };
}

/**
 * @param {import('../core/config.js').DeployHubConfig} config
 * @param {Record<string, string|undefined>} [env]
 * @param {{
 *   getGitShortSha?: () => string|null,
 *   now?: () => Date,
 * }} [options]
 * @returns {{
 *   imageName: string,
 *   imageTag: string,
 *   fullImage: string,
 *   latestImage: string,
 *   legacyLatestImage: string,
 *   tagSource: ImageTagSource,
 * }}
 */
export function resolveDockerImageRef(config, env = process.env, options = {}) {
  const imageName = env.DOCKER_IMAGE_NAME || config.project;
  const { imageTag, tagSource } = resolveImageTag(env, options);
  const registryUrl = env.DOCKER_REGISTRY_URL || '';

  const repository =
    registryUrl && !imageName.includes('/')
      ? `${registryUrl.replace(/\/$/, '')}/${imageName}`
      : imageName;

  return {
    imageName,
    imageTag,
    fullImage: `${repository}:${imageTag}`,
    latestImage: `${repository}:latest`,
    legacyLatestImage: `${config.project}:latest`,
    tagSource,
  };
}

/**
 * Runtime-only Dockerfile for frontend artifacts that already contain built static output.
 * Used when deploy must build from an artifact (no source / no package-lock).
 * @param {string} [buildOutput]
 * @returns {string}
 */
export function generateFrontendRuntimeDockerfile(buildOutput = 'dist') {
  const output = buildOutput.replace(/^\/+|\/+$/g, '') || 'dist';
  return `# Generated by DeployHub for artifact deploy (pre-built static output)
FROM nginx:alpine
COPY ${output}/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

/**
 * @param {string} jarRelativePath e.g. target/app.jar
 * @param {number} [port]
 */
export function generateSpringRuntimeDockerfile(jarRelativePath, port = 8080) {
  return `# Generated by DeployHub for artifact deploy (pre-built JAR)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY ${jarRelativePath} app.jar
EXPOSE ${port}
CMD ["java", "-jar", "app.jar"]
`;
}

/**
 * @param {string} binaryRelativePath e.g. bin/app
 * @param {number} [port]
 */
export function generateGoRuntimeDockerfile(binaryRelativePath, port = 8080) {
  return `# Generated by DeployHub for artifact deploy (pre-built Go binary)
FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY ${binaryRelativePath} ./app
RUN chmod +x ./app
EXPOSE ${port}
CMD ["./app"]
`;
}

/**
 * @param {string} publishDir
 * @param {number} [port]
 */
export function generateDotnetRuntimeDockerfile(publishDir = 'publish', port = 5000) {
  const dir = publishDir.replace(/^\/+|\/+$/g, '') || 'publish';
  return `# Generated by DeployHub for artifact deploy (pre-built .NET publish output)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY ${dir}/ .
EXPOSE ${port}
ENV ASPNETCORE_URLS=http://+:${port}
CMD ["dotnet", "App.dll"]
`;
}

/**
 * @param {string} framework
 * @returns {boolean}
 */
export function isFrontendStaticFramework(framework) {
  return ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'].includes(framework || '');
}

/**
 * Node-style backends whose generated Dockerfiles run npm ci and need a lockfile.
 * @param {string} framework
 */
export function isNodeBackendFramework(framework) {
  return ['express', 'nestjs', 'fastify', 'koa', 'nextjs'].includes(framework || '');
}

/**
 * Interpreted backends that install deps at image-build time (pip/composer/bundle/npm).
 * Their artifacts lack vendor/venv/node_modules, so standalone artifact rebuild is unsupported.
 * @param {string} framework
 */
export function isInterpretedBackendFramework(framework) {
  return [
    ...['express', 'nestjs', 'fastify', 'koa', 'nextjs'],
    'fastapi',
    'django',
    'flask',
    'laravel',
    'symfony',
    'rails',
  ].includes(framework || '');
}

/**
 * Human-readable dependency gap for interpreted backend artifact rebuilds.
 * @param {string} framework
 * @returns {{ ecosystem: string, missing: string, installCmd: string }}
 */
export function describeInterpretedBackendGap(framework) {
  if (isNodeBackendFramework(framework)) {
    return {
      ecosystem: 'Node',
      missing: 'package-lock.json / node_modules',
      installCmd: 'npm ci',
    };
  }
  if (['fastapi', 'django', 'flask'].includes(framework)) {
    return {
      ecosystem: 'Python',
      missing: 'a pre-installed virtualenv / site-packages (artifacts only ship requirements.txt + source)',
      installCmd: 'pip install',
    };
  }
  if (['laravel', 'symfony'].includes(framework)) {
    return {
      ecosystem: 'PHP',
      missing: 'vendor/ (Composer dependencies are not packaged into the artifact)',
      installCmd: 'composer install',
    };
  }
  if (framework === 'rails') {
    return {
      ecosystem: 'Ruby',
      missing: 'vendor/bundle / installed gems (artifacts only ship Gemfile + lock)',
      installCmd: 'bundle install',
    };
  }
  return {
    ecosystem: 'backend',
    missing: 'installed dependencies (not packaged into the artifact)',
    installCmd: 'dependency install',
  };
}

export default {
  resolveDockerImageRef,
  resolveImageTag,
  highResImageTagFallback,
  EXPLICIT_IMAGE_TAG_WARNING,
  generateFrontendRuntimeDockerfile,
  generateSpringRuntimeDockerfile,
  generateGoRuntimeDockerfile,
  generateDotnetRuntimeDockerfile,
  isFrontendStaticFramework,
  isNodeBackendFramework,
  isInterpretedBackendFramework,
  describeInterpretedBackendGap,
};
