/**
 * Shared Docker image naming for pipeline builds and deploy.
 */

import { resolveUniqueBuildStamp, highResBuildStamp } from './build-id.js';

/** @typedef {'explicit'|'git'|'ci'|'timestamp'|'buildId'} ImageTagSource */

export const EXPLICIT_IMAGE_TAG_WARNING =
  'DOCKER_IMAGE_TAG is set — reusing the same tag across deploys can leave Kubernetes pods on a stale image (imagePullPolicy defaults to IfNotPresent) unless imagePullPolicy is Always or a rollout restart runs.';

/** @deprecated use highResBuildStamp from build-id.js — kept for existing imports/tests */
export function highResImageTagFallback(now = new Date()) {
  return highResBuildStamp(now);
}

/**
 * Resolve image tag when DOCKER_IMAGE_TAG is unset: prefer config.buildId (same
 * pipeline identity as the artifact), else git SHA → CI id → high-res timestamp.
 *
 * @param {Record<string, string|undefined>} [env]
 * @param {{
 *   getGitShortSha?: () => string|null,
 *   now?: () => Date,
 *   buildId?: string,
 * }} [options]
 * @returns {{ imageTag: string, tagSource: ImageTagSource }}
 */
export function resolveImageTag(env = process.env, options = {}) {
  const explicit = env.DOCKER_IMAGE_TAG;
  if (explicit) {
    return { imageTag: explicit, tagSource: 'explicit' };
  }

  if (options.buildId) {
    return { imageTag: options.buildId, tagSource: 'buildId' };
  }

  const { stamp, source } = resolveUniqueBuildStamp(env, options);
  return { imageTag: stamp, tagSource: source };
}

/**
 * Same repository naming as resolveDockerImageRef, with an explicit tag.
 * Ignores DOCKER_IMAGE_TAG / git / CI — used when restoring a known buildId.
 *
 * @param {import('../core/config.js').DeployHubConfig} config
 * @param {Record<string, string|undefined>} [env]
 * @param {string} imageTag
 * @returns {{
 *   imageName: string,
 *   imageTag: string,
 *   fullImage: string,
 *   latestImage: string,
 *   legacyLatestImage: string,
 *   tagSource: ImageTagSource,
 * }}
 */
export function resolveDockerImageRefForTag(config, env = process.env, imageTag) {
  const imageName = env.DOCKER_IMAGE_NAME || config.project;
  const registryUrl = env.DOCKER_REGISTRY_URL || '';

  const repository =
    registryUrl && !imageName.includes('/')
      ? `${registryUrl.replace(/\/$/, '')}/${imageName}`
      : imageName;

  return {
    imageName,
    imageTag,
    fullImage: `${repository}:${imageTag}`,
    latestImage: `${repository}:latest`,
    legacyLatestImage: `${config.project}:latest`,
    tagSource: 'buildId',
  };
}

/**
 * Replace the tag portion of a docker image ref (handles registry:port/name:tag).
 * @param {string} imageRef
 * @param {string} newTag
 */
export function replaceDockerImageTag(imageRef, newTag) {
  const lastSlash = imageRef.lastIndexOf('/');
  const lastColon = imageRef.lastIndexOf(':');
  if (lastColon > lastSlash) {
    return `${imageRef.slice(0, lastColon)}:${newTag}`;
  }
  return `${imageRef}:${newTag}`;
}

/**
 * @param {import('../core/config.js').DeployHubConfig} config
 * @param {Record<string, string|undefined>} [env]
 * @param {{
 *   getGitShortSha?: () => string|null,
 *   now?: () => Date,
 * }} [options]
 * @returns {{
 *   imageName: string,
 *   imageTag: string,
 *   fullImage: string,
 *   latestImage: string,
 *   legacyLatestImage: string,
 *   tagSource: ImageTagSource,
 * }}
 */
export function resolveDockerImageRef(config, env = process.env, options = {}) {
  const { imageTag, tagSource } = resolveImageTag(env, {
    ...options,
    buildId: /** @type {{ buildId?: string }} */ (config).buildId,
  });
  return {
    ...resolveDockerImageRefForTag(config, env, imageTag),
    tagSource,
  };
}

/**
 * Runtime-only Dockerfile for frontend artifacts that already contain built static output.
 * Used when deploy must build from an artifact (no source / no package-lock).
 * @param {string} [buildOutput]
 * @returns {string}
 */
export function generateFrontendRuntimeDockerfile(buildOutput = 'dist') {
  const output = buildOutput.replace(/^\/+|\/+$/g, '') || 'dist';
  return `# Generated by DeployHub for artifact deploy (pre-built static output)
FROM nginx:alpine
COPY ${output}/ /usr/share/nginx/html/
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
`;
}

/**
 * @param {string} jarRelativePath e.g. target/app.jar
 * @param {number} [port]
 */
export function generateSpringRuntimeDockerfile(jarRelativePath, port = 8080) {
  return `# Generated by DeployHub for artifact deploy (pre-built JAR)
FROM eclipse-temurin:17-jre-alpine
WORKDIR /app
COPY ${jarRelativePath} app.jar
EXPOSE ${port}
CMD ["java", "-jar", "app.jar"]
`;
}

/**
 * @param {string} binaryRelativePath e.g. bin/app
 * @param {number} [port]
 */
export function generateGoRuntimeDockerfile(binaryRelativePath, port = 8080) {
  return `# Generated by DeployHub for artifact deploy (pre-built Go binary)
FROM alpine:3.19
WORKDIR /app
RUN apk add --no-cache ca-certificates
COPY ${binaryRelativePath} ./app
RUN chmod +x ./app
EXPOSE ${port}
CMD ["./app"]
`;
}

/**
 * @param {string} publishDir
 * @param {number} [port]
 */
export function generateDotnetRuntimeDockerfile(publishDir = 'publish', port = 5000) {
  const dir = publishDir.replace(/^\/+|\/+$/g, '') || 'publish';
  return `# Generated by DeployHub for artifact deploy (pre-built .NET publish output)
FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app
COPY ${dir}/ .
EXPOSE ${port}
ENV ASPNETCORE_URLS=http://+:${port}
CMD ["dotnet", "App.dll"]
`;
}

/**
 * @param {string} framework
 * @returns {boolean}
 */
export function isFrontendStaticFramework(framework) {
  return ['react', 'vue', 'angular', 'svelte', 'astro', 'vanilla'].includes(framework || '');
}

/**
 * Node-style backends whose generated Dockerfiles run npm ci and need a lockfile.
 * @param {string} framework
 */
export function isNodeBackendFramework(framework) {
  return ['express', 'nestjs', 'fastify', 'koa', 'nextjs'].includes(framework || '');
}

/**
 * Interpreted backends that install deps at image-build time (pip/composer/bundle/npm).
 * Their artifacts lack vendor/venv/node_modules, so standalone artifact rebuild is unsupported.
 * @param {string} framework
 */
export function isInterpretedBackendFramework(framework) {
  return [
    ...['express', 'nestjs', 'fastify', 'koa', 'nextjs'],
    'fastapi',
    'django',
    'flask',
    'laravel',
    'symfony',
    'rails',
  ].includes(framework || '');
}

/**
 * Human-readable dependency gap for interpreted backend artifact rebuilds.
 * @param {string} framework
 * @returns {{ ecosystem: string, missing: string, installCmd: string }}
 */
export function describeInterpretedBackendGap(framework) {
  if (isNodeBackendFramework(framework)) {
    return {
      ecosystem: 'Node',
      missing: 'package-lock.json / node_modules',
      installCmd: 'npm ci',
    };
  }
  if (['fastapi', 'django', 'flask'].includes(framework)) {
    return {
      ecosystem: 'Python',
      missing: 'a pre-installed virtualenv / site-packages (artifacts only ship requirements.txt + source)',
      installCmd: 'pip install',
    };
  }
  if (['laravel', 'symfony'].includes(framework)) {
    return {
      ecosystem: 'PHP',
      missing: 'vendor/ (Composer dependencies are not packaged into the artifact)',
      installCmd: 'composer install',
    };
  }
  if (framework === 'rails') {
    return {
      ecosystem: 'Ruby',
      missing: 'vendor/bundle / installed gems (artifacts only ship Gemfile + lock)',
      installCmd: 'bundle install',
    };
  }
  return {
    ecosystem: 'backend',
    missing: 'installed dependencies (not packaged into the artifact)',
    installCmd: 'dependency install',
  };
}

export default {
  resolveDockerImageRef,
  resolveDockerImageRefForTag,
  replaceDockerImageTag,
  resolveImageTag,
  highResImageTagFallback,
  EXPLICIT_IMAGE_TAG_WARNING,
  generateFrontendRuntimeDockerfile,
  generateSpringRuntimeDockerfile,
  generateGoRuntimeDockerfile,
  generateDotnetRuntimeDockerfile,
  isFrontendStaticFramework,
  isNodeBackendFramework,
  isInterpretedBackendFramework,
  describeInterpretedBackendGap,
};
